name: Show last tweet

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * *'
      
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install Package Dependencies
        run: |-
          options(download.file.method = "libcurl")
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_github('gadenbuie/tweetrmd@main')"
          Rscript -e "remotes::install_github('rstudio/webshot2')"
          Rscript -e "install.packages('rtweet')"
      - name: Run script
        env:
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        run: |-
          Rscript -e "source('script.R')"
      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v4.4.0
        with:
          branch: master
          commit_message: "Update the latest tweet"
          
